behavior_planning:
  default: {}
control:
  ControllerSelection:
    lateral_controller_type: MPC
  MPC:
    dt: 0.05
    fallback_mode:
      w_ax: 10.0
      w_dax: 9.0
      w_ddelta: 95.0
      w_delta: 30.0
      w_epsi: 50.0
      w_ey: 60.0
      w_r: 9.0
      w_v: 22.0
      w_vy: 20.0
    horizon: 15
    mapping_mode:
      w_ax: 10.0
      w_dax: 9.0
      w_ddelta: 80.0
      w_delta: 30.0
      w_epsi: 50.0
      w_ey: 50.0
      w_r: 9.0
      w_v: 20.0
      w_vy: 15.0
    max_speed_for_scaling: 10.0
    mpc_speed_scaling_factor: 1.0
    racing_mode:
      w_ax: 0.2
      w_dax: 2.0
      w_ddelta: 10.0
      w_delta: 2.0
      w_epsi: 20.0
      w_ey: 15.0
      w_r: 1.0
      w_v: 10.0
      w_vy: 1.0
  PurePursuit:
    lookahead_distance: 1.0
    max_steer_angle: 1.0
  SpeedControl:
    max_throttle: 1.0
    pid_kd: 0.005
    pid_ki: 0.05
    pid_kp: 0.5
    post_loop_closure:
      curvature_lookahead: 5
      curvature_speed_factor: 20
      min_speed: 8.0
      target_speed: 12.0
    pre_loop_closure:
      curvature_lookahead: 3
      curvature_speed_factor: 20
      min_speed: 6.0
      target_speed: 10.0
  Stanley:
    k_gain: 1.4
  Vehicle:
    Cd: 0.3
    Crr: 0.014
    Iz: 150.0
    a_lat_max: 16.0
    ax_max: 16.0
    ax_min: -16.0
    car_mass: 255.0
    delta_dot_max: 350.0
    delta_max: 25.0
    friction_scale: 1.4
    front_axle_distance: 0.6
    frontal_area: 1.2
    h_cg: 0.25
    lat_stiff_coeff: 38.40
    max_steer_angle: 25.0
    rho_air: 1.2
    wheel_base: 1.55
local_planning:
  trajectory:
    default_speed: 5.0
    lane_offset: 1.5
    lookahead_distance: 5.0
    max_accumulated_midpoints: 150
    max_cone_distance: 3.0
    max_x_diff_for_pairing: 5.0
    num_waypoints: 20
    planner_clustering_eps: 10.0
    planner_roi_angle: 90.0
    planner_roi_distance: 25.0
    poly_degree: 3
    safety_margin: 0.5
    spline_smoothing_factor: 0.5
    waypoint_spacing: 2.0
localization:
  localization:
    alpha_velocity: 0.1
    ref_wgs84_altitude: 0.0
    ref_wgs84_latitude: 47.641467991978416
    ref_wgs84_longitude: -122.14016501105924
    use_user_defined_ref_wgs84_position: true
    yaw_filter_alpha: 0.5
mapping:
  association_threshold: 1.5
  lc:
    cooldown_updates: 100
    max_error: 0.75
    min_cones: 20
    min_pairs: 5
    search_radius: 15.0
    trigger_distance: 8.0
  provisional cone:
    confirmation_threshold: 2
    ttl: 15
perception:
  time_sync:
    slop: 0.1
    time_offset : 0.08
  camera_cone_detection:
    min_bbox_area: 10
    target_image_height: 240
    target_image_width: 320
    visualize_lidar_on_camera: false
  camera_extrinsics:
    rotation_pitch: 0.0
    rotation_roll: 0.0
    rotation_yaw: 0.0
    translation_x: -0.43
    translation_y: -0.15
    translation_z: 0.82
  camera_hsv_blue:
    hue_max: 110
    hue_min: 95
    saturation_min: 75
    value_min: 100
  camera_hsv_orange:
    hue_max: 20
    hue_min: 10
    saturation_min: 100
    value_min: 100
  camera_hsv_window_size:
    window_size: 25
  camera_hsv_yellow:
    hue_max: 50
    hue_min: 20
    saturation_min: 20
    value_min: 60
  camera_image_processing:
    bilateral_filter_diameter: 15
    enable_preprocessing: true
    gaussian_blur_sigma: 2.0
  camera_intrinsics:
    focal_length_x: 320.0
    focal_length_y: 320.0
    principal_point_x: 320.0
    principal_point_y: 240.0
  camera_right_extrinsics:
    rotation_pitch: 0.0
    rotation_roll: 0.0
    rotation_yaw: 0.0
    translation_x: -0.43
    translation_y: 0.15
    translation_z: 0.82
  lidar_clustering:
    dbscan_eps: 1.0
    dbscan_min_points: 3
  lidar_cone_detection:
    cone_max_radius: 0.7
    cone_min_points: 1
    cone_min_radius: 0.0
  lidar_extrinsics:
    rotation_pitch: 0.0
    rotation_roll: 0.0
    rotation_yaw: 0.0
    translation_x: 0.6
    translation_y: 0.0
    translation_z: 0.1
  lidar_ground_removal:
    ransac_distance_threshold: 0.01
    ransac_iterations: 50
  lidar_roi_extraction:
    x_max: 35.0
    x_min: 0.0
    y_max: 18.0
    y_min: -18.0
    z_max: 10.0
    z_min: -10.0
planning:
  path_planner:
    max_edge_length: 40.0
    max_path_distance: 60.0
    path_obstacle_threshold: 1.5
    spline_smoothing_factor: 1.2
    weight_angle: 1.2
    weight_dist: 0.5
system:
  logging:
    enable_logging: true
  main_loop_rate: 1000.0
  visualization:
    enable_visualization: true
